export default [
  'Yes!',
  'Maybe...',
  'No',
  'Git off my lawn!',
  'Better not tell you now!',
  'I am not here to judge you.',
  "It's not for me to say.",
  "You're unintelligent.",
  'Maybe another day.',
  "I don't even know what Marbles is.",
  'Ask your mother, she should know!',
  'Do not... forget that.',
  'Outlook not so good.',
  'It works on my machine.',
  'I love your accent.',
  'Let me think about it.',
  'PEW PEW!',
  'Asked nobody, ever.',
  'Did you Google it already?',
  'Have you tried turning it off and on again?',
  'You may rely on it.',
  'I have a joke about CSS, but it has no class.',
  'Try harder.',
  "That's what she said.",
  "Don't listen to the BaldBeardedBuilder.",
  'BaldBeardedBuilder talks garbage.',
  'The answer lies where you least expect it.',
  'Hell, no!',
  '42',
  '101',
  'The cake is a lie.',
  'SCOPE CREEP!',
  '*bot left the room*',
  'You only know, what you know',
  "Why didn't the number 4 get into the nightclub? Because he is 2 square.",
  'Only you can answer that question',
];
