export default [
  'Yes!',
  'Maybe...',
  'No',
  'Git off my lawn!',
  'Better not tell you now!',
  'I am not here to judge you',
  "It's not for me to say",
  "You're unintelligent",
  'Maybe another day',
  "I don't even know what Marbles is",
  'Ask your mother, she should know!',
  'Do not... forget that',
  'Outlook not so good',
  'It works on my machine',
  'I love your accent',
  'Let me think about it',
  'PEW PEW!',
  'Asked nobody, ever',
  'Did you Google it already?',
  'Have you tried turning it off and on again?',
  'You may rely on it',
  'I have a joke about CSS, but it has no class',
  'Try harder',
  "That's what she said.",
  "Don't listen to the BaldBeardedBuilder",
  'BaldBeardedBuilder talks garbage',
  'The answer lies where you least expect it',
  'Hell, no!',
  '42',
  '101',
  'The cake is a lie',
  'SCOPE CREEP!',
  '*bot left the room*',
  'You only know, what you know',
  "Why didn't the number 4 get into the nightclub? Because he is 2 square",
  'Only you can answer that question',
  '[object Object]',
  "Can't access null of undefined",
  'NullReferenceException',
  'NaN',
  'Undefined is not a function',
  '404 Not Found',
  "21 is what you're looking for",
  'Cake is the answer to all of your problems!',
  'Elm is dope.',
  "There's an npm package for that",
  "I'll gladly not give you the answer!",
  'It is bigger on the inside',
  'Be yourself, everyone else is already taken',
  'The answer is 42',
  'Have you tried asking Stack Overflow?',
  'console.error([object Object])',
  "I'll Google that for you",
  "I'm just an 8 ball! I'm not built for that kind of question!",
  'Computer says no',
  'Error 500 P4nth3rBrain not found',
  'Are these really the questions I was brought here to answer?',
  'Calculating...',
  'Did you really ask me this?',
  'Linus would drop you an answer',
  "Don't listen to the voices in your head",
  "My therapist says it's fiiiiiinnnnne!",
  'Um, no!',
  'I think not',
  'return responses[ Math.floor(Math.random() * responses.length) ]',
  'What an idiot',
  'getBallResponse()',
  'Perfect',
  'What? That must be a US thing.',
  'Compiling...',
  "Ask me again and I'll throw you into full dive VR hell",
  'Let me ask my supervisor about that',
  'Things only have the meaning YOU give them',
  'Covid-19',
  'Ask whitep4nth3r',
  'Uh, ask me again after COVID',
  'Let me have a loop',
  'The antidote is on its way',
  "You're not going to like the answer",
  "Do you even know what you're doing?",
  'That just made my ball hurt',
  'Mark as duplicate',
  'Cannot predict now',
  'My sources say no',
  'Very doubtful',
  'Signs point to yes',
];
